# Generated by Django 4.2 on 2023-05-04 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name', max_length=200, verbose_name='Name')),
                ('city', models.CharField(help_text='Enter city', max_length=100, verbose_name='City')),
                ('address', models.CharField(help_text='Enter address', max_length=200, verbose_name='address')),
                ('telephone', models.CharField(blank=True, help_text='Enter telephone number', max_length=20, verbose_name='telephone')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name of Region', max_length=200, verbose_name='Name of Region')),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(help_text='Enter surname', max_length=100, verbose_name='Surname')),
                ('name', models.CharField(help_text='Enter name', max_length=100, verbose_name='Name')),
                ('job', models.CharField(blank=True, default=None, help_text='Enter job', max_length=200, verbose_name='Job')),
                ('id_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uktio.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(help_text='Enter login', max_length=100, unique=True, verbose_name='Login')),
                ('password', models.CharField(help_text='Enter password', max_length=200, verbose_name='Password')),
                ('last_logon', models.DateTimeField(blank=True, help_text='Enter DateTime last logon', null=True, verbose_name='DateTime last logon')),
                ('last_wrong_logon', models.DateTimeField(blank=True, help_text='Enter DateTime last bad logon', null=True, verbose_name='DateTime last bad logon')),
                ('is_superuser', models.BooleanField(default=False, help_text='True - Superuser, defaulf=False', verbose_name='Is user Superadmin')),
                ('is_view', models.BooleanField(default=True, help_text='True - only view, default=True', verbose_name='Is user only view')),
                ('organization', models.ManyToManyField(help_text='Organization', to='uktio.organization')),
                ('region', models.ManyToManyField(help_text='Regions', to='uktio.region')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uktio.region'),
        ),
        migrations.AddField(
            model_name='organization',
            name='subordinate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='uktio.organization'),
        ),
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name', max_length=200, verbose_name='Name')),
                ('description', models.CharField(blank=True, help_text='Enter description', max_length=200, null=True, verbose_name='Description')),
                ('id_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uktio.organization')),
            ],
        ),
    ]
