# Generated by Django 4.2 on 2023-05-06 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uktio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cabinet',
            old_name='id_organization',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='workers',
            old_name='id_organization',
            new_name='organization',
        ),
    ]
