# Generated by Django 4.2 on 2023-05-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uktio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='region',
            field=models.ManyToManyField(help_text='Regions', to='uktio.region'),
        ),
    ]
