# Generated by Django 4.2 on 2023-05-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uktio', '0002_users_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='users',
            field=models.ManyToManyField(help_text='Organization', to='uktio.organization'),
        ),
    ]
