# Generated by Django 4.2 on 2023-05-04 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uktio', '0003_users_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='users',
            new_name='organization',
        ),
    ]
