# Generated by Django 4.2 on 2023-05-04 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uktio', '0004_rename_users_users_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='organization',
            new_name='subordinate',
        ),
    ]
