# Generated by Django 4.2 on 2023-05-04 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uktio', '0005_rename_organization_users_subordinate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='region',
        ),
        migrations.AddField(
            model_name='users',
            name='region',
            field=models.ForeignKey(default=None, help_text='Regions', on_delete=django.db.models.deletion.CASCADE, to='uktio.region'),
            preserve_default=False,
        ),
    ]
