# Generated by Django 4.2 on 2023-05-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uktio', '0006_remove_users_region_users_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='id_region',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='id_subordinate',
            new_name='subordinate',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='subordinate',
            new_name='organization',
        ),
        migrations.RemoveField(
            model_name='users',
            name='region',
        ),
        migrations.AddField(
            model_name='users',
            name='region',
            field=models.ManyToManyField(help_text='Regions', to='uktio.region'),
        ),
    ]
